nginx:
    container_name: nginx
    build: ./nginx
    links:
        - node1:node1
        - node2:node2
    ports:
        - "80:80"
    volumes_from:
        - logs

node1:
    container_name: node1
    build: ./node
    links:
        - redis
        - mongo
    ports:
        - "8080:8080"
    volumes_from:
      - logs
    environment:
      - LOG_FILE=/var/log/node/node1.log
node2:
    container_name: node2
    build: ./node
    links:
        - redis
        - mongo
    ports:
        - "8081:8080"
    volumes_from:
      - logs
    environment:
      - LOG_FILE=/var/log/node/node2.log

redis:
    container_name: redis
    image: redis
    ports:
        - "6379"

mongoData:
  container_name: data-container-mongo
  image: busybox:latest
  volumes:
    - ./data/mongo:/data/db
  entrypoint: /bin/sh
mongo:
    container_name: mongo
    image: mongo
    ports:
        - "27017"
    volumes_from:
        - mongoData

logs:
  container_name: data-container-logs
  image: busybox:latest
  volumes:
    - "./data/logs/:/var/log/:rw"
    - "./data/logs/nginx/:/var/log/nginx/:rw"
  entrypoint: /bin/sh
