# Set nginx base image
FROM nginx

# File Author / Maintainer
MAINTAINER Waleed Samy <waleed_samy@ymail.com>

# Copy custom configuration file from the current directory
COPY nginx.conf /etc/nginx/nginx.conf
